// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swghcmyqracwifpdfyap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Z2hjbXlxcmFjd2lmcGRmeWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTkyNzMsImV4cCI6MjA3MTc3NTI3M30.El9QwmA4aMu1-S-NMvgm5gmFYcZNZicB3-0BXFc-bV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});